name: great_wall
description: A protocol for providing Kerckhoffian, 0-trust and deviceless coercion-resistance in self-custody.
version: 0.1.0-dev
homepage: https://t3infosecurity.com
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

dependencies:
  convert: ^3.1.2
  cryptography: ^2.7.0
  hashlib: ^1.16.0
  t3_hashviz:
    git:
      url: git@github.com:T3-InfoSec/t3-hashviz-dart.git
      ref: development
  fractal:
    git:
      url: git@github.com:T3-InfoSec/t3-fractals-dart.git
      ref: fix/import-the-fractal-class-into-the-dart-module
  t3_crypto_objects:
    git:
      url: git@github.com:T3-InfoSec/t3-crypto-objects-dart.git
      ref: development
