name: great_wall
description: A protocol for providing Kerckhoffian, 0-trust, deviceless coercion-resistance in self-custody.
version: 0.1.0-dev
homepage: https://t3informationsecurity.com

environment:
  sdk: ^3.4.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

dependencies:
  hashlib: ^1.16.0
